# Site settings
title: Musings about technology
email: ilkka.anttonen@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Random articles about random things, mainly on technology. At first
  a lot will have to do with containers (Docker).
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sirile.github.io" # the base hostname & protocol for your site
twitter_username: ilkkaanttonen
github_username:  SirIle
github:
  user: sirile
  project: sirile.github.io

# Build settings
markdown: kramdown
highlighter: rouge
#future: true
timezone: Europe/Helsinki
sass:
  style: compressed
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
